language: python
python: 3.7
deploy:
  provider: pypi
  user: danielarnason
  password:
    secure: iCV8LjSRzxeMEtjHR1SQ2iJ9hG2lJc+NKykxVcOdJ9WSeUI8Uhai6Dpat7jPGHCuDZw+0z9IUpuphnUS9Wmh+vB69fKSsJ0vWEf1UOJlxl9iKgmqoMAjR5gk1SSmfec1vVgqN9IQrlYsXKyr1aHktxlDRr1i3Wwf9dKPuJe5lS2eWdXPyo/r+wK7hTDDXZ0lcWMMNe9QxM/VjaAO0A3QeYZOnmXFTCBdhon/2q7ESM9wChYMxPLNv0rVbQ11NM94bkGAF2LLKk5TeCVw8WTYqUXDlFby/a8H8kPJ6jwgDBfne9C25zox/jSDRiIM89OO7rOzup3jY6pdgBYaQ4m/yCkiwH1SrAXAWVmh+MFeSCETGf2DgUMwNro7en5MI1BnKbGPPo1WLLQnrcWnrT82aizX5ak9LIhQjRlNUFUPget5d9e9C/AlxdVXvrgCEeZheykHOhI0TcnBd7Sy+c9W0FKAqwgbAhASS23WWza7w6uaxJ00GCP3P4RidZiX6+5klDQZB33ywv040tPDXsgme4AfyjoLIXLYWoVnzAIeMqs2v13CS3ZLU4ThCXiiG7n+tzwt4c/BSa95qeEGOKgN/nmbxe/pXhLtVx/AWukGj6sWFG4Bq1n2mxNBF3nF5OFt2+sceF/MismWpqiX2zwPry34uD8eVqWftGlGhL0TxKk=
  on:
    tags: true
    branch: master
